#! /usr/bin/env bash
#export PS4="\$LINENO: "
#set -xv

log_base="batch.o"
viewCommand="squeue -u $LOGNAME"
rate=1 # per second

log_files=(${log_base}*)

if [ $# -eq 0 ]; then
    # echo "No arguments supplied"
    numlines=12
else
    numlines=$1
fi

# check for multiple log files, take last or wait
if [ ${#log_files[@]} -gt 0 ]; then
    log_last=${log_files[-1]}
else
    echo "looking for logfile..."
    while [ ! -e ${log_base}* ]; do
        sleep 1s
    done
    log_last=${log_base}*
fi

# run watch command
watch -n ${rate} "\
    ${viewCommand} && \
    printf '\n# Step:\n\n' && \
    wc -l out_progress.txt && \
    printf '\n# Log:\n\n' && \
    tail -n ${numlines} ${log_last} && \
    printf '\n# .sta:\n\n' && \
    tail -n 4 *.sta \
"
