site_name: matmdl docs
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.sections
    - navigation.instant
    - search.suggest
    - navigation.indexes
  custom_dir: overrides
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  # - toc:
  #     permalink: true
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [..]
        options:
          show_submodules: true
          show_symbol_type_heading: true
          group_by_category: true
          show_root_heading: true


nav:
  - index.md
  - Installation: install.md
  - Getting Started:
    - Input: input.md
    - Output: output.md
  - Theory:
    - Intro: theory.md
    - Objective: objective.md
    - Extra: theory2.md
  - API: 
    - API/index.md
    - run: API/run.md
    - plot: API/plot.md
    - other: 
      - core: API/core.md
      - engines: API/engines.md
      - objectives: API/objectives.md
      - models: API/models.md
