name: CI
on:
  push:
    branches: [ develop ]
  pull_request: { branches: [develop, test_ci] }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout scikit-opt
        uses: actions/checkout@v2
        with:
          repository: shimanek/scikit-optimize

      - name: install prerequirements
        run: pip install -U pip

      - name: install scikit-optimize
        run: |
          echo $PATH
          git clone https://github.com/shimanek/scikit-optimize
          cd scikit-optimize
          pip install -e .
          cd ..
        shell: bash

      - name: Install package
        run: pip install -e matmdl/.

      - name: Test
        run: |
          cd tests
          python3 -m unittest
