name: CI
on:
  push:
    branches: [ develop ]
  pull_request: { branches: [develop] }
  # schedule: [ cron: '20 16 * * 6' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install scikit-opt
          pip install -e .matmdl
# ^ note that scikit-opt is stale and doesn't play nicely with more recent numpy changes
# meaning that automated testing needs to pull from an updated fork and `pip -e install` it

      - name: Test
        run: |
          cd tests
          python3 -m unittest
